using System.Text;
using PokemonGreen.MapGen.Models;

namespace PokemonGreen.MapGen.Services;

public static class CodeGenerator
{
    /// <summary>
    /// Generates a C# class that extends MapDefinition from the given map model.
    /// </summary>
    /// <param name="map">The map model to generate code for.</param>
    /// <param name="className">The name of the generated class (without "Map" suffix).</param>
    /// <returns>The generated C# code as a string.</returns>
    public static string GenerateMapClass(MapJsonModel map, string className)
    {
        var sb = new StringBuilder();

        // Generate the map ID from the class name (PascalCase to snake_case)
        var mapId = ToSnakeCase(className);

        sb.AppendLine("// Auto-generated by PokemonGreen.MapGen");
        sb.AppendLine("namespace PokemonGreen.Core.Maps;");
        sb.AppendLine();
        sb.AppendLine($"public class {className}Map : MapDefinition");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {className}Map Instance {{ get; }} = new();");
        sb.AppendLine($"    public override string Id => \"{mapId}\";");
        sb.AppendLine($"    public override string Name => \"{EscapeString(map.Name)}\";");
        sb.AppendLine($"    public override int Width => {map.Width};");
        sb.AppendLine($"    public override int Height => {map.Height};");
        sb.AppendLine();
        sb.AppendLine("    public override TileMap CreateTileMap()");
        sb.AppendLine("    {");
        sb.AppendLine("        var map = new TileMap(Width, Height);");

        // Generate SetBaseTile calls for each tile
        if (map.Tiles != null && map.Tiles.Length > 0)
        {
            sb.AppendLine();
            for (int y = 0; y < map.Tiles.Length && y < map.Height; y++)
            {
                var row = map.Tiles[y];
                if (row == null) continue;

                for (int x = 0; x < row.Length && x < map.Width; x++)
                {
                    var tileId = row[x];
                    // Only generate calls for non-zero tiles (0 is the default)
                    if (tileId != 0)
                    {
                        sb.AppendLine($"        map.SetBaseTile({x}, {y}, {tileId});");
                    }
                }
            }
        }

        sb.AppendLine();
        sb.AppendLine("        return map;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Converts PascalCase to snake_case.
    /// </summary>
    private static string ToSnakeCase(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        var sb = new StringBuilder();
        for (int i = 0; i < input.Length; i++)
        {
            var c = input[i];
            if (char.IsUpper(c))
            {
                if (i > 0)
                    sb.Append('_');
                sb.Append(char.ToLowerInvariant(c));
            }
            else
            {
                sb.Append(c);
            }
        }
        return sb.ToString();
    }

    /// <summary>
    /// Escapes special characters in a string for C# string literals.
    /// </summary>
    private static string EscapeString(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        return input
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\n", "\\n")
            .Replace("\r", "\\r")
            .Replace("\t", "\\t");
    }
}
