<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\PokemonGreen.SwitchToolboxCli.Core\PokemonGreen.SwitchToolboxCli.Core.csproj" />
    <ProjectReference Include="..\PokemonGreen.SwitchToolboxCli.Formats\PokemonGreen.SwitchToolboxCli.Formats.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\lib\oo2core_8_win64.dll"
          Condition="Exists('..\..\lib\oo2core_8_win64.dll')"
          CopyToOutputDirectory="PreserveNewest"
          Link="oo2core_8_win64.dll" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
